// Catalogue des permissions RBAC — infrastructure du schéma d'autorisation, pas une donnée
// métier/de démonstration (au même titre qu'une migration). Partagé entre seed.ts (dev, crée aussi
// des comptes de démo) et bootstrap-production.ts (prod, ne crée qu'une Organization + un compte
// SUPER_ADMIN réels, voir ce fichier pour le raisonnement complet).
export const BASE_PERMISSIONS = [
  { key: "users.view", description: "Voir les utilisateurs" },
  { key: "users.create", description: "Créer un utilisateur" },
  { key: "roles.view", description: "Voir les rôles" },
  { key: "permissions.view", description: "Voir les permissions" },
  { key: "organizations.view", description: "Voir l'organisation" },
  { key: "hotels.view", description: "Voir les hôtels" },
  { key: "hotels.create", description: "Créer un hôtel" },
  { key: "hotels.update", description: "Modifier un hôtel" },
  { key: "departments.view", description: "Voir les départements" },
  { key: "departments.create", description: "Créer un département" },
  { key: "departments.update", description: "Modifier un département" },
  { key: "activities.view", description: "Voir les activités" },
  { key: "activities.create", description: "Créer une activité" },
  { key: "activities.update", description: "Modifier une activité" },
  { key: "cost-centers.view", description: "Voir les centres de coûts" },
  { key: "cost-centers.create", description: "Créer un centre de coûts" },
  { key: "cost-centers.update", description: "Modifier un centre de coûts" },
  // Phase 5 — format plat "resource.action", uniformisé avec le reste du catalogue (Étape 7,
  // durcissement RBAC). Utilisait à l'origine "finance.<ressource>.<action>" (brief §30) ; aplati
  // en "finance-<ressource>.<action>" pour ne plus être le seul domaine imbriqué — voir la
  // migration prisma/migrations/*_flatten_finance_permission_keys pour le remappage des clés
  // existantes (Permission.key réécrit en place, RolePermission référence permissionId donc aucune
  // attribution existante n'est perdue).
  { key: "finance-categories.view", description: "Voir les catégories financières" },
  { key: "finance-categories.create", description: "Créer une catégorie financière" },
  { key: "finance-categories.update", description: "Modifier une catégorie financière" },
  { key: "finance-cash-accounts.view", description: "Voir les caisses" },
  { key: "finance-cash-accounts.create", description: "Créer une caisse" },
  { key: "finance-cash-accounts.update", description: "Modifier une caisse / saisir une opération" },
  { key: "finance-bank-accounts.view", description: "Voir les comptes bancaires" },
  { key: "finance-bank-accounts.create", description: "Créer un compte bancaire" },
  { key: "finance-bank-accounts.update", description: "Modifier un compte bancaire / saisir une opération" },
  { key: "finance-revenues.view", description: "Voir les recettes" },
  { key: "finance-revenues.create", description: "Créer une recette" },
  { key: "finance-expenses.view", description: "Voir les dépenses" },
  { key: "finance-expenses.create", description: "Créer une dépense" },
  { key: "finance-expenses.update", description: "Modifier une dépense en brouillon" },
  { key: "finance-expenses.submit", description: "Soumettre une dépense" },
  { key: "finance-expenses.approve", description: "Approuver ou rejeter une dépense" },
  { key: "finance-expenses.pay", description: "Marquer une dépense comme payée" },
  { key: "finance-expenses.book", description: "Comptabiliser une dépense" },
  { key: "finance-budgets.view", description: "Voir les budgets" },
  { key: "finance-budgets.create", description: "Créer un budget" },
  { key: "finance-budgets.update", description: "Modifier un budget / ajouter une ligne" },
  { key: "finance-summary.view", description: "Voir le résumé financier" },
  // Phase 6
  { key: "finance-invoices.view", description: "Voir les factures" },
  { key: "finance-invoices.create", description: "Créer une facture" },
  { key: "finance-invoices.update", description: "Modifier une facture en brouillon" },
  { key: "finance-invoices.issue", description: "Émettre une facture" },
  { key: "finance-invoices.cancel", description: "Annuler une facture" },
  { key: "finance-payments.view", description: "Voir les paiements" },
  { key: "finance-payments.create", description: "Enregistrer un paiement" },
  { key: "finance-credit-notes.view", description: "Voir les avoirs" },
  { key: "finance-credit-notes.create", description: "Émettre un avoir" },
  // Phase 7 — format plat "resource.action", cohérent Phase 3-4 (domaine non-finance).
  { key: "room-types.view", description: "Voir les types de chambres" },
  { key: "room-types.create", description: "Créer un type de chambre" },
  { key: "room-types.update", description: "Modifier un type de chambre" },
  { key: "rooms.view", description: "Voir les chambres" },
  { key: "rooms.create", description: "Créer une chambre" },
  { key: "rooms.update", description: "Modifier une chambre" },
  { key: "guests.view", description: "Voir les clients" },
  { key: "guests.create", description: "Créer un client" },
  { key: "guests.update", description: "Modifier un client" },
  { key: "reservations.view", description: "Voir les réservations" },
  { key: "reservations.create", description: "Créer une réservation" },
  { key: "reservations.update", description: "Modifier une réservation en attente" },
  { key: "reservations.confirm", description: "Confirmer une réservation" },
  { key: "reservations.check-in", description: "Enregistrer l'arrivée d'un client" },
  { key: "reservations.check-out", description: "Enregistrer le départ d'un client" },
  { key: "reservations.cancel", description: "Annuler une réservation" },
  { key: "reservations.no-show", description: "Marquer une réservation comme non présentée" },
  // Phase 8 — format plat "resource.action", cohérent Phase 7.
  { key: "employees.view", description: "Voir les employés" },
  { key: "employees.create", description: "Créer un employé" },
  { key: "employees.update", description: "Modifier un employé" },
  { key: "work-schedules.view", description: "Voir le planning" },
  { key: "work-schedules.create", description: "Créer un créneau de planning" },
  { key: "work-schedules.update", description: "Modifier un créneau de planning" },
  { key: "attendance.view", description: "Voir les présences" },
  { key: "attendance.create", description: "Pointer une arrivée" },
  { key: "attendance.clock-out", description: "Pointer un départ" },
  { key: "leave-requests.view", description: "Voir les demandes de congé" },
  { key: "leave-requests.create", description: "Créer une demande de congé" },
  { key: "leave-requests.update", description: "Modifier une demande de congé en attente" },
  { key: "leave-requests.approve", description: "Approuver une demande de congé" },
  { key: "leave-requests.reject", description: "Rejeter une demande de congé" },
  { key: "leave-requests.cancel", description: "Annuler une demande de congé" },
  { key: "payslips.view", description: "Voir les bulletins de paie" },
  { key: "payslips.create", description: "Créer un bulletin de paie" },
  { key: "payslips.update", description: "Modifier un bulletin de paie en brouillon" },
  { key: "payslips.finalize", description: "Finaliser un bulletin de paie" },
  { key: "payslips.mark-paid", description: "Marquer un bulletin de paie comme payé" },
  // Phase 9 — format plat "resource.action", cohérent Phase 7-8. "Facture fournisseur"/"paiement"
  // n'ont pas de clés dédiées : ils réutilisent finance-expenses.* (Expense.supplierId/
  // purchaseOrderId, additifs).
  { key: "suppliers.view", description: "Voir les fournisseurs" },
  { key: "suppliers.create", description: "Créer un fournisseur" },
  { key: "suppliers.update", description: "Modifier un fournisseur" },
  { key: "purchase-requests.view", description: "Voir les demandes d'achat" },
  { key: "purchase-requests.create", description: "Créer une demande d'achat" },
  { key: "purchase-requests.update", description: "Modifier une demande d'achat en attente" },
  { key: "purchase-requests.approve", description: "Approuver une demande d'achat" },
  { key: "purchase-requests.reject", description: "Rejeter une demande d'achat" },
  { key: "purchase-requests.cancel", description: "Annuler une demande d'achat" },
  { key: "purchase-orders.view", description: "Voir les commandes d'achat" },
  { key: "purchase-orders.create", description: "Créer une commande d'achat" },
  { key: "purchase-orders.update", description: "Modifier une commande d'achat en brouillon" },
  { key: "purchase-orders.send", description: "Envoyer une commande d'achat au fournisseur" },
  { key: "purchase-orders.cancel", description: "Annuler une commande d'achat" },
  { key: "goods-receipts.view", description: "Voir les réceptions" },
  { key: "goods-receipts.create", description: "Enregistrer une réception" },
  // Phase 10 — format plat "resource.action", cohérent Phase 7-9.
  { key: "housekeeping-tasks.view", description: "Voir les tâches de ménage" },
  { key: "housekeeping-tasks.create", description: "Signaler une chambre à nettoyer" },
  { key: "housekeeping-tasks.clean", description: "Marquer une chambre comme nettoyée" },
  { key: "housekeeping-tasks.inspect", description: "Marquer une chambre comme inspectée" },
  { key: "assets.view", description: "Voir les actifs" },
  { key: "assets.create", description: "Créer un actif" },
  { key: "assets.update", description: "Modifier un actif" },
  { key: "maintenance-requests.view", description: "Voir les demandes de maintenance" },
  { key: "maintenance-requests.create", description: "Créer une demande de maintenance" },
  { key: "maintenance-requests.update", description: "Modifier une demande de maintenance en attente" },
  { key: "maintenance-requests.approve", description: "Approuver une demande de maintenance" },
  { key: "maintenance-requests.reject", description: "Rejeter une demande de maintenance" },
  { key: "maintenance-requests.cancel", description: "Annuler une demande de maintenance" },
  { key: "maintenance-interventions.view", description: "Voir les interventions de maintenance" },
  { key: "maintenance-interventions.create", description: "Planifier une intervention de maintenance" },
  { key: "maintenance-interventions.update", description: "Modifier une intervention planifiée" },
  { key: "maintenance-interventions.start", description: "Démarrer une intervention de maintenance" },
  { key: "maintenance-interventions.complete", description: "Terminer une intervention de maintenance" },
  { key: "maintenance-interventions.cancel", description: "Annuler une intervention de maintenance" },
  // Phase 11 — moteur de rapports (§54). Une seule clé cette phase (un seul rapport, "financial").
  { key: "reports.financial.view", description: "Voir/exporter le rapport financier" },
  // Phase 12 — notifications (§35) + audit trail (§37).
  { key: "notifications.view", description: "Voir ses notifications" },
  { key: "notifications.mark-read", description: "Marquer ses notifications comme lues" },
  { key: "audit-logs.view", description: "Voir le journal d'audit" },
  { key: "finance-budgets.check-overspend", description: "Vérifier les dépassements budgétaires et générer des alertes" },
  // Phase 13 — format plat "resource.action", cohérent Phase 7-10.
  { key: "warehouses.view", description: "Voir les entrepôts" },
  { key: "warehouses.create", description: "Créer un entrepôt" },
  { key: "warehouses.update", description: "Modifier un entrepôt" },
  { key: "products.view", description: "Voir les produits et leur stock" },
  { key: "products.create", description: "Créer un produit" },
  { key: "products.update", description: "Modifier un produit" },
  { key: "products.check-low-stock", description: "Vérifier les seuils de stock minimum et générer des alertes" },
  { key: "stock-movements.view", description: "Voir les mouvements de stock" },
  { key: "stock-movements.create", description: "Enregistrer une entrée/sortie/consommation/perte de stock" },
  { key: "stock-movements.transfer", description: "Transférer du stock entre entrepôts" },
  { key: "stock-movements.adjustment", description: "Ajuster un stock après inventaire physique" },
  // Étape 7 (durcissement, Priority 6) — métriques opérationnelles du process API (mémoire,
  // volumétrie/latence des requêtes) : donnée plateforme transverse à tous les tenants, pas une
  // ressource organisation/hôtel. Volontairement absente du sous-ensemble HOTEL_ADMIN de seed.ts —
  // seul SUPER_ADMIN doit voir la charge globale du serveur.
  { key: "system-monitoring.view", description: "Voir les métriques de supervision système" },
];
